#!/bin/sh
# Configure GitHub SSH key authentication

default_email="$(git config --get user.email)"
if [ -z "$default_email" ]; then
	printf 'Enter email: '
	read -r email
else
	printf 'Enter email (%s): ' "$default_email"
	read -r email
	[ -z "$email" ] && email="$default_email"
fi

ssh-keygen -qt rsa -b 4096 -C "$email" || exit 1
eval > /dev/null "$(ssh-agent -s)" || exit 1
ssh-add -q ~/.ssh/id_rsa || exit 1

printf 'Add the key to https://github.com/settings/ssh/new\n'
cat ~/.ssh/id_rsa.pub
printf 'Press return to continue'
read -r

ssh -T git@github.com || exit 1
