#!/bin/sh
# Set up the system
#
# This script assumes that the repository is succesfully cloned to $HOME.

# ---Helpers---
yesno_prompt() {
	prompt="$1"
	if_yes="$2"

	while true; do
		printf '%s' "$prompt"
		read -r yesno
		case "$yesno" in
			yes)
				$if_yes
				break
				;;
			no)
				break
				;;
		esac
	done
}

# ---Entry point---
cd || exit 1

git config status.showUntrackedFiles no

yesno_prompt 'Do you wish to configure github ssh key authentication(yes/no)?' './wizards/github-wizard'

case "$(uname)" in
	OpenBSD)
		rm .profile
		ln -s .profile.openbsd .profile
		;;
esac
