;; init.el – my lovely emacs configuration :^)
(load-file "~/.emacs.d/package.el")
(load-file "~/.emacs.d/darwin.el")
(load-file "~/.emacs.d/path.el")
(load-file "~/.emacs.d/selectrum.el")
(load-file "~/.emacs.d/magit.el")
(load-file "~/.emacs.d/cc-mode.el")
(load-file "~/.emacs.d/project.el")
(load-file "~/.emacs.d/eradio.el")
(load-file "~/.emacs.d/littering.el")
(load-file "~/.emacs.d/org.el")
(load-file "~/.emacs.d/compile.el")
(load-file "~/.emacs.d/misc.el")
(load-file "~/.emacs.d/modus.el")
(load-file "~/.emacs.d/browse.el")
(load-file "~/.emacs.d/markdown.el")
(load-file "~/.emacs.d/irc.el")
(load-file "~/.emacs.d/games.el")
(load-file "~/.emacs.d/dired.el")
(load-file "~/.emacs.d/docs.el")
(load-file "~/.emacs.d/lines.el")
(load-file "~/.emacs.d/rss.el")
(load-file "~/.emacs.d/web.el")
(load-file "~/.emacs.d/custom.el")
(load-file "~/.emacs.d/toggle.el")
(load-file "~/.emacs.d/insert-kaomoji")

;; use weekly agenda as splash screen / default buffer
(setq inhibit-splash-screen t)
(org-agenda-list)
(delete-other-windows)
