;; init.el – my lovely emacs configuration :^)
(load-file "~/.emacs.d/package.el")
(load-file "~/.emacs.d/darwin.el")
(load-file "~/.emacs.d/selectrum.el")
(load-file "~/.emacs.d/magit.el")
(load-file "~/.emacs.d/cc-mode.el")
(load-file "~/.emacs.d/project.el")
(load-file "~/.emacs.d/eradio.el")
(load-file "~/.emacs.d/littering.el")
(load-file "~/.emacs.d/org.el")
(load-file "~/.emacs.d/misc.el")
(load-file "~/.emacs.d/custom.el")
